name: Release Permit Golang Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'
      - name: Build and test package
        run: |
          go build -v ./...
#          go test -v ./...
      - name: Release package
        run: |
          go get github.com/goreleaser/goreleaser
          goreleaser --rm-dist
